services:
  - type: web
    name: megh-x-mini-pairing
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PAIRING_MODE
        value: "true"
      - key: OWNER_NUMBER
        value: "254795314221"
      - key: OWNER_NAME
        value: "killer"
      - key: PREFIX
        value: "."
      - key: BOT_NAME
        value: "MEGH X-MINI"
